<script>
const LOGO="__LOGO__";
const MISSIONS={
 lunar:{id:"lunar",name:"Lunar Program",num:"AP-01",dest:"Lunar surface, Mare Serenitatis station",accent:"#C9CDD3",tone:"silver",
  bg:"The Lunar Program is ASTRAEUS's longest running equipment line. Every item is rated for dust, thermal swing and long shifts under low light. Finishes are brushed silver and warm white, with navy panels where grip matters."},
 mars:{id:"mars",name:"Mars Expedition",num:"AP-04",dest:"Mars, Arcadia Planitia forward camp",accent:"#A39189",tone:"dust",
  bg:"The Mars Expedition line is built for long duration field work far from resupply. Gear is repairable, modular, and marked with large legible identifiers for use with gloves. A muted dust tone identifies the collection."},
 deepfield:{id:"deepfield",name:"Deep Field",num:"AP-07",dest:"Outer system survey, beyond the belt",accent:"#5B7FA6",tone:"steel",
  bg:"Deep Field equipment is designed for isolation. Long battery life, mechanical redundancy, and instruments that keep working with nothing else around. The collection carries a cold steel blue accent."},
 orbital:{id:"orbital",name:"Orbital Operations",num:"AP-02",dest:"Low Earth orbit, station and transit",accent:"#0E73B3",tone:"orbital",
  bg:"Orbital Operations supplies crews living and working in orbit. Compact, light, and secured against drift, with Earth blue as its accent. This is the line most visitors start with."},
 frontier:{id:"frontier",name:"Frontier Series",num:"AP-09",dest:"Unmapped terrain, Earth and offworld",accent:"#7D8B99",tone:"slate",
  bg:"The Frontier Series is the rugged end of the catalog. Reinforced shells, oversized latches, and field serviceable parts. A quiet slate accent marks the series."},
 earthside:{id:"earthside",name:"Earthside",num:"AP-00",dest:"Home. Cities, roads, coastlines.",accent:"#2E9BD8",tone:"sky",
  bg:"Earthside is the ASTRAEUS design philosophy applied to ordinary days. The same materials and markings, scaled for a commute, a workshop, a weekend. Sky blue accent."}
};
const DIV={EXP:"ASTRAEUS EXPEDITIONARY",ORB:"ASTRAEUS ORBITAL",FLD:"ASTRAEUS FIELD SYSTEMS",WCH:"ASTRAEUS WATCH DIVISION",LAB:"ASTRAEUS EQUIPMENT LAB",MAT:"ASTRAEUS MATERIALS DIVISION",FRO:"ASTRAEUS FRONTIER OPERATIONS"};
const CATS={watches:{name:"Watches",blurb:"Precision watches inspired by aerospace instrumentation, navigation and mission equipment."},
 storage:{name:"Watch Storage",blurb:"Protective cases, travel cases and modular storage built like field hardware."},
 equipment:{name:"Field Equipment",blurb:"Durable storage, tools, bags, utility products and exploration equipment."},
 everyday:{name:"Everyday Equipment",blurb:"Useful daily objects designed with the same industrial philosophy."},
 apparel:{name:"Apparel",blurb:"Shirts, jackets, hats, patches and mission inspired technical clothing."},
 firearms:{name:"Firearms",blurb:"A restrained, professional catalog of field firearms and accessories. Transfer through licensed dealers only."}};
// kind drives the illustration. av: in|low|out
const P=[
 // WATCHES
 {id:"w-orb-01",cat:"watches",type:"Chronograph",fam:"ASTRAEUS ORBITAL",name:"Orbital Chronograph",model:"OW-01",price:2850,mission:"orbital",div:"WCH",kind:"watch",dial:"navy",strap:"bracelet",av:"in",series:"ORBITAL SERIES",
  desc:"Flagship manual wind chronograph with tachymeter bezel and a dial calibrated for orbital elapsed time.",materials:"316L stainless case, sapphire crystal with inner anti reflective coating, brushed steel bracelet",dims:"40.5 mm case, 13.2 mm thick, 47 mm lug to lug",weight:"142 g on bracelet",
  specs:{Movement:"ASTRAEUS cal. A-311 manual wind, 60 hour reserve",Functions:"Hours, minutes, small seconds, 30 minute and 12 hour counters",Crystal:"Sapphire, domed",WaterResistance:"100 m",Lume:"Warm white Super LumiNova on hands and markers",Caseback:"Engraved Earth horizon, serial numbered"}},
 {id:"w-orb-02",cat:"watches",type:"Three hand",fam:"ASTRAEUS ORBITAL",name:"Orbital Field Automatic",model:"OW-02",price:1850,mission:"orbital",div:"WCH",kind:"watch",dial:"navy",strap:"nato",av:"in",series:"ORBITAL SERIES",
  desc:"Automatic three hand field watch with a 24 hour inner ring for station timekeeping.",materials:"316L stainless case, sapphire crystal, woven textile strap",dims:"38 mm case, 11 mm thick",weight:"78 g",
  specs:{Movement:"ASTRAEUS cal. A-200 automatic, 42 hour reserve",Functions:"Hours, minutes, seconds, date, 24 hour ring",Crystal:"Sapphire, flat",WaterResistance:"100 m",Strap:"20 mm quick release"}},
 {id:"w-lun-01",cat:"watches",type:"Chronograph",fam:"ASTRAEUS LUNAR",name:"Lunar Chronograph",model:"LW-01",price:3400,mission:"lunar",div:"WCH",kind:"watch",dial:"silver",strap:"bracelet",av:"in",series:"EXPEDITION SERIES",
  desc:"Silver dial chronograph with a lunar surface relief caseback. Rated for thermal cycling from minus 40 to 80 C.",materials:"316L stainless case, sapphire, silver sunray dial",dims:"42 mm case, 13.8 mm thick",weight:"151 g",
  specs:{Movement:"ASTRAEUS cal. A-311 manual wind",Functions:"Chronograph, tachymeter, small seconds",ThermalRating:"minus 40 to 80 C",WaterResistance:"100 m",Caseback:"Lunar relief, laser etched"}},
 {id:"w-lun-02",cat:"watches",type:"GMT",fam:"ASTRAEUS LUNAR",name:"Lunar GMT",model:"LW-02",price:2650,mission:"lunar",div:"WCH",kind:"watch",dial:"silver",strap:"rubber",av:"low",series:"EXPEDITION SERIES",
  desc:"Dual time GMT with a 24 hour bezel in navy and silver for two reference clocks.",materials:"Titanium grade 2 case, sapphire, fluororubber strap",dims:"41 mm case, 12.4 mm thick",weight:"96 g",
  specs:{Movement:"ASTRAEUS cal. A-250 automatic GMT",Functions:"Hours, minutes, seconds, second time zone",Bezel:"Bidirectional 24 hour, ceramic insert",WaterResistance:"200 m"}},
 {id:"w-dfd-01",cat:"watches",type:"Diver",fam:"ASTRAEUS DEEP FIELD",name:"Deep Field Diver",model:"DW-01",price:2950,mission:"deepfield",div:"WCH",kind:"watch",dial:"black",strap:"rubber",av:"in",series:"EXPEDITION SERIES",
  desc:"600 m diver with helium valve and oversized lume plots for low light environments.",materials:"Titanium grade 5 case, sapphire, ceramic bezel",dims:"43 mm case, 14.5 mm thick",weight:"118 g",
  specs:{Movement:"ASTRAEUS cal. A-200 automatic",WaterResistance:"600 m, helium escape valve",Bezel:"Unidirectional 120 click",Lume:"Large plots, 10 hour visibility",Strap:"22 mm rubber with extension"}},
 {id:"w-dfd-02",cat:"watches",type:"Three hand",fam:"ASTRAEUS DEEP FIELD",name:"Deep Field Survey",model:"DW-02",price:2100,mission:"deepfield",div:"WCH",kind:"watch",dial:"black",strap:"bracelet",av:"in",series:"EXPEDITION SERIES",
  desc:"Antimagnetic survey watch with soft iron inner case and a compass style seconds hand.",materials:"316L stainless, soft iron inner case, sapphire",dims:"40 mm case, 12 mm thick",weight:"136 g",
  specs:{Movement:"ASTRAEUS cal. A-200 automatic",Antimagnetic:"to 80,000 A/m",WaterResistance:"150 m",Crystal:"Sapphire, domed"}},
 {id:"w-exp-01",cat:"watches",type:"Field",fam:"ASTRAEUS EXPEDITION",name:"Expedition Field 38",model:"EW-01",price:1450,mission:"frontier",div:"WCH",kind:"watch",dial:"navy",strap:"nato",av:"in",series:"EXPEDITION SERIES",
  desc:"Entry point to the catalog. Mechanical field watch with hacking seconds and a drilled lug case.",materials:"316L stainless, sapphire, textile strap",dims:"38 mm case, 10.8 mm thick",weight:"72 g",
  specs:{Movement:"ASTRAEUS cal. A-100 hand wound, 56 hour reserve",Functions:"Hours, minutes, hacking seconds",WaterResistance:"100 m",Strap:"20 mm, two included"}},
 {id:"w-exp-02",cat:"watches",type:"Chronograph",fam:"ASTRAEUS EXPEDITION",name:"Expedition Chronograph 42",model:"EW-02",price:2400,mission:"mars",div:"WCH",kind:"watch",dial:"black",strap:"nato",av:"in",series:"EXPEDITION SERIES",
  desc:"Mars Expedition issue chronograph with oversized pushers for gloved operation.",materials:"Bead blasted titanium, sapphire",dims:"42 mm case, 14 mm thick",weight:"104 g",
  specs:{Movement:"ASTRAEUS cal. A-311 manual wind",Pushers:"Oversized, glove rated",WaterResistance:"100 m",Caseback:"Mission AP-04 engraving"}},
 // STORAGE
 {id:"c-w2",cat:"storage",type:"Watch case",name:"Field Watch Case Two",model:"FC-200",price:290,mission:"frontier",div:"FLD",kind:"case",size:2,av:"in",series:"FIELD SYSTEMS",
  desc:"Two watch hard case with a twist latch, replaceable webbing and a window for a mission disc.",materials:"Glass filled polymer shell, machined aluminum end caps, closed cell foam",dims:"200 × 150 × 85 mm",weight:"640 g",
  specs:{Capacity:"2 watches, up to 46 mm",Closure:"Twist and pull latch, stainless pin",Interior:"Two cushion foam, removable",WaterResistance:"IP67, pressure equalization valve",Impact:"1.5 m drop onto concrete, loaded",MissionCompatibility:"All programs, disc window accepts any mission disc"}},
 {id:"c-w4",cat:"storage",type:"Watch case",name:"Field Watch Case Four",model:"FC-400",price:390,mission:"frontier",div:"FLD",kind:"case",size:4,av:"in",series:"FIELD SYSTEMS",
  desc:"Four watch case in the compact format. Same latch and webbing system as the FC-200.",materials:"Glass filled polymer shell, aluminum end caps, closed cell foam",dims:"180 × 140 × 70 mm per tier, stacked",weight:"890 g",
  specs:{Capacity:"4 watches",Closure:"Twist and pull latch",Interior:"Four cushion foam",WaterResistance:"IP67",Impact:"1.5 m drop rated"}},
 {id:"c-w4p",cat:"storage",type:"Watch case",name:"Field Watch Case Four Premier",model:"FC-400P",price:520,mission:"lunar",div:"MAT",kind:"case",size:4,prem:true,av:"low",series:"FIELD SYSTEMS",
  desc:"Premier edition with brushed aluminum lid panels, leather lined interior and a serial plate.",materials:"Aluminum lid, polymer base, vegetable tanned leather lining",dims:"190 × 145 × 75 mm",weight:"1,020 g",
  specs:{Capacity:"4 watches",Closure:"Twist and pull latch, keyed",Interior:"Leather lined cushions",WaterResistance:"IP54",SerialPlate:"Individually numbered"}},
 {id:"c-g4",cat:"storage",type:"Gear case",name:"Tech Case Tall",model:"GC-400",price:340,mission:"orbital",div:"FLD",kind:"case",size:0,tall:true,av:"in",series:"FIELD SYSTEMS",
  desc:"Deep storage case for watches plus tools, cables, a light and everyday carry.",materials:"Glass filled polymer, aluminum",dims:"220 × 160 × 120 mm",weight:"1,100 g",
  specs:{Capacity:"2 watches plus modular tray",Closure:"Twist and pull latch",Interior:"Pick and pluck foam over watch cushions",WaterResistance:"IP67",Impact:"2 m drop rated"}},
 {id:"c-disc",cat:"storage",type:"Accessory",name:"Mission Disc Set",model:"MD-06",price:48,mission:"",div:"LAB",kind:"disc",av:"in",series:"FIELD SYSTEMS",
  desc:"Six interchangeable art discs for the case window. One for each ASTRAEUS program.",materials:"Anodized aluminum, printed and sealed",dims:"38 mm diameter",weight:"6 g each",
  specs:{Contents:"Six discs, one per program",Fit:"All FC and GC series windows",Finish:"Anodized, UV sealed"}},
 // FIELD EQUIPMENT
 {id:"e-duffel",cat:"equipment",type:"Bag",name:"Transit Duffel 45",model:"FD-45",price:260,mission:"frontier",div:"EXP",kind:"bag",av:"in",series:"EXPEDITION SERIES",
  desc:"45 liter weather resistant duffel with stowable harness and a welded navy base.",materials:"840D nylon, TPU laminated base, aluminum hardware",dims:"58 × 32 × 28 cm",weight:"1.2 kg",
  specs:{Volume:"45 L",Carry:"Duffel handles, stowable backpack harness",Weather:"Water resistant, storm flap zipper",Access:"Full length U zip"}},
 {id:"e-pack",cat:"equipment",type:"Bag",name:"Survey Pack 28",model:"FP-28",price:240,mission:"deepfield",div:"EXP",kind:"pack",av:"in",series:"EXPEDITION SERIES",
  desc:"Daypack with instrument sleeve, external tool loops and a frame sheet.",materials:"500D nylon, foam frame sheet",dims:"50 × 30 × 20 cm",weight:"980 g",
  specs:{Volume:"28 L",Sleeve:"Fits 16 inch instrument or laptop",Loops:"Four external tool loops",Frame:"Removable HDPE sheet"}},
 {id:"e-light",cat:"equipment",type:"Light",name:"Field Light 900",model:"FL-900",price:135,mission:"mars",div:"LAB",kind:"light",av:"in",series:"FIELD SYSTEMS",
  desc:"900 lumen rechargeable light with a warm white emitter and a momentary tail switch.",materials:"Machined aluminum, type III anodized",dims:"128 mm long, 25 mm head",weight:"112 g with cell",
  specs:{Output:"900 lm high, 30 lm low, 2 lm moonlight",Runtime:"3 h high, 60 h low",Charging:"USB C, 21700 cell included",Rating:"IPX8, 1 m drop"}},
 {id:"e-tool",cat:"equipment",type:"Tool",name:"Service Multitool",model:"FT-12",price:165,mission:"orbital",div:"LAB",kind:"tool",av:"in",series:"FIELD SYSTEMS",
  desc:"Twelve function multitool with spring strap tool, driver bits and locking blade.",materials:"Stainless frame, titanium scales",dims:"105 mm closed",weight:"160 g",
  specs:{Functions:"12",Blade:"78 mm, locking",Drivers:"Bit holder, 4 bits included",Sheath:"Navy nylon, belt loop"}},
 {id:"e-cont",cat:"equipment",type:"Container",name:"Modular Storage Container 10",model:"MC-10",price:95,mission:"orbital",div:"FLD",kind:"container",av:"in",series:"FIELD SYSTEMS",
  desc:"Stackable 10 liter container with gasketed lid and label plate. Locks to its neighbors.",materials:"Polypropylene, silicone gasket",dims:"400 × 300 × 120 mm",weight:"720 g",
  specs:{Volume:"10 L",Stacking:"Interlocking corners, 6 high",Seal:"Gasketed, dust and splash",Label:"Replaceable plate, dry erase"}},
 {id:"e-bottle",cat:"equipment",type:"Bottle",name:"Thermal Bottle 750",model:"TB-750",price:58,mission:"earthside",div:"MAT",kind:"bottle",av:"in",series:"EARTHSIDE CERTIFIED",
  desc:"Vacuum bottle with a wide mouth, a silver cap and laser etched volume marks.",materials:"18/8 stainless, powder coated navy",dims:"265 mm tall, 78 mm diameter",weight:"410 g",
  specs:{Volume:"750 ml",Thermal:"24 h cold, 12 h hot",Cap:"Wide mouth, carry loop",Finish:"Navy powder coat, silver cap"}},
 // EVERYDAY
 {id:"d-note",cat:"everyday",type:"Notebook",name:"Mission Log Notebook",model:"ML-A5",price:28,mission:"earthside",div:"LAB",kind:"notebook",av:"in",series:"EARTHSIDE CERTIFIED",
  desc:"A5 hardcover log with numbered pages, a silver ribbon and a contour map end paper.",materials:"Navy linen cover, 100 gsm paper",dims:"148 × 210 mm",weight:"320 g",
  specs:{Pages:"192, numbered",Ruling:"Dot grid 5 mm",Binding:"Thread sewn, lies flat",Extras:"Ribbon, elastic, rear pocket"}},
 {id:"d-pen",cat:"everyday",type:"Pen",name:"Pressurized Field Pen",model:"FP-01",price:44,mission:"orbital",div:"LAB",kind:"pen",av:"in",series:"EARTHSIDE CERTIFIED",
  desc:"Machined aluminum pen with a pressurized cartridge that writes upside down and in the cold.",materials:"Aluminum, stainless clip",dims:"135 mm",weight:"28 g",
  specs:{Cartridge:"Pressurized, black",Operation:"Twist",Temperature:"minus 30 to 120 C",Finish:"Silver, navy band"}},
 {id:"d-wallet",cat:"everyday",type:"Wallet",name:"Card Carrier",model:"CC-06",price:62,mission:"earthside",div:"MAT",kind:"wallet",av:"in",series:"EARTHSIDE CERTIFIED",
  desc:"Six card aluminum carrier with a pull tab and RFID shielding.",materials:"Aluminum, elastic",dims:"88 × 56 × 10 mm",weight:"42 g",
  specs:{Capacity:"6 cards",Shielding:"RFID",Finish:"Brushed silver or navy"}},
 {id:"d-mug",cat:"everyday",type:"Mug",name:"Station Mug",model:"SM-12",price:34,mission:"orbital",div:"MAT",kind:"mug",av:"in",series:"EARTHSIDE CERTIFIED",
  desc:"Double wall stainless mug with a sliding lid and ASTRAEUS orbital markings.",materials:"18/8 stainless",dims:"350 ml",weight:"240 g",
  specs:{Volume:"350 ml",Lid:"Sliding, dishwasher safe",Thermal:"Double wall vacuum"}},
 {id:"d-charger",cat:"everyday",type:"Power",name:"Power Cell 20",model:"PC-20",price:89,mission:"deepfield",div:"LAB",kind:"cell",av:"low",series:"FIELD SYSTEMS",
  desc:"20,000 mAh power cell in a rubber armored aluminum shell with a state of charge dial.",materials:"Aluminum, TPU armor",dims:"150 × 72 × 24 mm",weight:"380 g",
  specs:{Capacity:"20,000 mAh",Output:"65 W USB C, 18 W USB A",Display:"Analog charge dial",Rating:"IP54"}},
 // APPAREL
 {id:"a-jacket",cat:"apparel",type:"Jacket",name:"Flight Shell Jacket",model:"AJ-01",price:385,mission:"orbital",div:"EXP",kind:"jacket",av:"in",series:"ORBITAL SERIES",
  desc:"Three layer shell with a stowable hood, chest instrument pocket and a program patch panel.",materials:"3L nylon shell, taped seams",dims:"Sizes XS to XXL",weight:"520 g",
  specs:{Waterproof:"20,000 mm",Breathability:"20,000 g",Pockets:"Two hand, one chest, one sleeve",Patch:"Loop panel on left shoulder"}},
 {id:"a-tee",cat:"apparel",type:"Shirt",name:"Program Tee",model:"AT-02",price:48,mission:"lunar",div:"EXP",kind:"tee",av:"in",series:"EARTHSIDE CERTIFIED",
  desc:"Heavyweight cotton tee with a small chest insignia and a back print of the Lunar Program manifest.",materials:"220 gsm combed cotton",dims:"Sizes XS to XXL",weight:"230 g",
  specs:{Fabric:"220 gsm cotton",Fit:"Regular",Print:"Water based ink, chest and back"}},
 {id:"a-cap",cat:"apparel",type:"Hat",name:"Field Cap",model:"AC-01",price:42,mission:"frontier",div:"EXP",kind:"cap",av:"in",series:"EXPEDITION SERIES",
  desc:"Six panel cap in navy ripstop with a silver insignia and a metal slide adjuster.",materials:"Nylon ripstop",dims:"One size",weight:"70 g",
  specs:{Panels:"6",Closure:"Metal slide",Brim:"Pre curved"}},
 {id:"a-patch",cat:"apparel",type:"Patch",name:"Program Patch Set",model:"AP-06",price:36,mission:"",div:"EXP",kind:"patch",av:"in",series:"MISSION READY",
  desc:"Six embroidered program patches with hook backing. One for each ASTRAEUS mission.",materials:"Embroidered twill, hook backing",dims:"76 mm",weight:"8 g each",
  specs:{Contents:"Six patches",Backing:"Hook",Fit:"Jacket patch panel, packs"}},
 {id:"a-fleece",cat:"apparel",type:"Fleece",name:"Station Fleece",model:"AF-03",price:165,mission:"deepfield",div:"MAT",kind:"fleece",av:"in",series:"ORBITAL SERIES",
  desc:"Grid fleece quarter zip with a silver chest zipper and division marking on the sleeve.",materials:"Polartec style grid fleece",dims:"Sizes XS to XXL",weight:"340 g",
  specs:{Fabric:"Grid fleece, 200 gsm",Zip:"Quarter length, silver",Sleeve:"Division marking"}},
 {id:"a-pants",cat:"apparel",type:"Pants",name:"Field Pant",model:"AP-04",price:175,mission:"mars",div:"EXP",kind:"pants",av:"low",series:"EXPEDITION SERIES",
  desc:"Articulated field pant with reinforced knees, a tool pocket and a gusseted crotch.",materials:"Stretch nylon canvas",dims:"Waist 28 to 40",weight:"480 g",
  specs:{Fabric:"Nylon canvas, 4 way stretch",Knees:"Reinforced, pad pocket",Pockets:"Seven"}},
 // FIREARMS
 {id:"f-rifle",cat:"firearms",type:"Rifle",name:"FR-7 Field Rifle",model:"FR-7",price:2190,mission:"frontier",div:"FRO",kind:"rifle",av:"in",series:"FIELD SYSTEMS",ffl:true,
  desc:"Bolt action field rifle in a navy composite stock with a silver bolt handle. Supplied with a hard case.",materials:"Stainless barreled action, composite stock",dims:"Overall 1,040 mm, 20 inch barrel",weight:"3.4 kg",
  specs:{Action:"Bolt, controlled feed",Chambering:"6.5 mm",Barrel:"20 inch, threaded, stainless",Magazine:"Detachable, 5 round",Trigger:"Adjustable, 1.0 to 1.8 kg",Case:"FC series hard case included"}},
 {id:"f-pistol",cat:"firearms",type:"Pistol",name:"SP-9 Service Pistol",model:"SP-9",price:890,mission:"orbital",div:"FRO",kind:"pistol",av:"in",series:"FIELD SYSTEMS",ffl:true,
  desc:"Striker fired 9 mm service pistol with an optics ready slide and a navy polymer frame.",materials:"Stainless slide, polymer frame",dims:"Overall 185 mm, 4 inch barrel",weight:"680 g",
  specs:{Action:"Striker fired",Chambering:"9 mm",Capacity:"15 round, two magazines",Slide:"Optics ready, silver finish",Sights:"Tritium, warm white"}},
 {id:"f-shot",cat:"firearms",type:"Shotgun",name:"FS-12 Utility Shotgun",model:"FS-12",price:1150,mission:"mars",div:"FRO",kind:"shotgun",av:"low",series:"FIELD SYSTEMS",ffl:true,
  desc:"Pump action utility shotgun with an 18.5 inch barrel and a composite stock.",materials:"Steel receiver, composite stock",dims:"Overall 970 mm",weight:"3.2 kg",
  specs:{Action:"Pump",Chambering:"12 gauge, 3 inch",Barrel:"18.5 inch, cylinder bore",Capacity:"5 plus 1",Sights:"Ghost ring"}},
 {id:"f-sling",cat:"firearms",type:"Accessory",name:"Rifle Sling",model:"RS-02",price:68,mission:"frontier",div:"FRO",kind:"sling",av:"in",series:"FIELD SYSTEMS",
  desc:"Two point adjustable sling in navy webbing with silver hardware. Ships without restriction.",materials:"Nylon webbing, aluminum hardware",dims:"Adjustable 90 to 140 cm",weight:"120 g",
  specs:{Type:"Two point, quick adjust",Hardware:"Aluminum, silver",Width:"32 mm"}},
 {id:"f-rcase",cat:"firearms",type:"Accessory",name:"Long Gun Hard Case",model:"LC-110",price:310,mission:"frontier",div:"FLD",kind:"longcase",av:"in",series:"FIELD SYSTEMS",
  desc:"Lockable 110 cm hard case with pressure valve and pick and pluck foam. Ships without restriction.",materials:"Polymer shell, stainless hinge pins",dims:"1,100 × 380 × 150 mm",weight:"5.6 kg",
  specs:{Length:"110 cm interior",Locks:"Two padlock points",Rating:"IP67, airline approved",Interior:"Pick and pluck foam"}},
];
const BYID=Object.fromEntries(P.map(p=>[p.id,p]));
const fmt=n=>"$"+n.toLocaleString("en-US");
</script>
